### PR TITLE
German translations for aeon.cash, CLI, GUI and contributing.md

### PR DESCRIPTION
**Pull request by AmorbiaCacoa**
Hi there,
It's my first work on Aeon (and Github in general). I translated all the files like in the spanish and polish translations.
Let me know if anything is missing, otherwise I will create a funding proposal within the next few days.

### CODE REVIEW

**Review by BigslimVdub — CHANGES_REQUESTED** [review]
Vielen Dank für Ihren Beitrag. Wenn Sie git auf Ihrem lokalen PC installiert haben, können Sie bitte alle Ihre Commits zu einem Squash zusammenfassen? Wenn Sie Hilfe benötigen, finden Sie hier einen Link zur Vorgehensweise: https://gist.github.com/patik/b8a9dc5cd356f9f6f980

**Comment by BigslimVdub** [comment]
Also, on the readme.german.gui.md can you change the licence at the header to ``Urheberrecht (c) 2014-2019, AEON, The Monero Project``. Thanks!

**Comment by AmorbiaCacoa** [comment]
Hi there,
I changed the date after the Copyright. I also squashed the commits together. It wasn't as easy shown in the link you provided and did therefore not work as nicely as expected. It still shows 3 commits instead of only 1.
Would this be ok? Otherwise I can just start over again und simply upload the files.

**Review by BigslimVdub — APPROVED** [review]

**Comment by AmorbiaCacoa** [comment]
Thank you for merging!
Please let me know if there are more translations to do, I'm happy to help.

**Pull request merged**
